### ISSUE TITLE
Geyser crash

### ISSUE THREAD

**Issue by Hellohi3654** [GeyserMC/GeyserAndroid#17] opened 2021-01-12 14:51 UTC
**Describe the bug**

If the app is compiled with a newer version of Geyser 
When starting Geyer in the app is crashes the whole app
**To Reproduce**

1. Compile Geyser-android with latest version of Geyser 
2. Start Geyser
3. App Crashes
**Expected behavior**

App not to crash 
**Screenshots / Videos**

**Android OS Version**

10
**Android App Version**

Custom
**Geyser Version**

Not sure when this started happens or what changed to make this happen
**Minecraft: Bedrock Edition Version**

**Additional Context**

**Comment by rtm516** [comment] 2021-01-12 22:53
This is caused by the protocol dependency not being updated in this repo, I have fixed this locally and will push the change once I get the builds fixed with the new CI.

**Comment by Hellohi3654** [comment] 2021-01-13 11:28
ok thanks

**Comment by rtm516** [comment] 2021-01-13 12:00
This has been fixed with https://github.com/GeyserMC/GeyserAndroid/commit/5c3f93038e41e542a3a5997d886c2b60016334e0

**Closed by rtm516** 2021-01-13 12:00 UTC
