### ISSUE TITLE
1.16.220

### ISSUE THREAD

**Issue by digra55** [GeyserMC/GeyserAndroid#21] opened 2021-04-22 15:36 UTC
When will the update to 1.16.220?
If you come close to the block and jump on it, it returns back, and also on the stairs and in the water.

**Comment by POTATOEXE** [comment] 2021-04-22 18:07
How does geyser work with 1.16.220 bye you
Due to the update geyser stop working by me

**Comment by Camotoy** [comment] 2021-04-22 20:02
Duplicate of #20. Thanks for reporting anyway!

**Closed by Camotoy** 2021-04-22 20:02 UTC
